# Generated by Django 6.0 on 2025-12-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_updated_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supserset', models.BinaryField(blank=True, null=True)),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutsession')),
            ],
        ),
    ]
