# Generated by Django 6.0 on 2025-12-21 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsets',
            old_name='exercise',
            new_name='exercise_value',
        ),
    ]
