# Generated by Django 6.0 on 2025-12-21 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_rename_exercise_workoutsets_exercise_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='exercise_type',
            field=models.CharField(choices=[('Weight and Reps', 'Weight And Reps'), ('Distance and Time', 'Distance And Time'), ('Weight and Distance', 'Weight And Distance'), ('Weight and Time', 'Weight And Time'), ('Reps and Distance', 'Reps And Distance'), ('Reps and Time', 'Reps And Time'), ('Weight', 'Weight'), ('Reps', 'Reps'), ('Distance', 'Distance'), ('Time', 'Time')], default='Weight and Reps'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='default_unit',
            field=models.CharField(choices=[('lbs', 'Lbs'), ('kg', 'Kg'), ('bodyweight', 'Bw'), ('time', 'Time'), ('distance', 'Distance')], default='lbs'),
        ),
    ]
