# Generated by Django 6.0 on 2025-12-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_exercises_exercise_type_alter_equipment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='muscle_group',
        ),
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.CharField(max_length=95, unique=True),
        ),
        migrations.AlterField(
            model_name='musclegroups',
            name='muscle_group_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='muscle_group',
            field=models.ManyToManyField(to='workout.musclegroups'),
        ),
    ]
