# Generated by Django 6.0 on 2026-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_equipment_equipment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsets',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsets',
            name='distance_mi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsets',
            name='reps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='workoutsets',
            name='time_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsets',
            name='time_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsets',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsets',
            name='weight_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
